### ISSUE TITLE
When I install the component I get a dependency error.

### ISSUE THREAD

**Issue by santiblanko** [Akryum/vue-share-components#1]
The solution is install manually 

` npm install --save-dev less-loader less`

I tried to configure a basic component without "less component" (Only css)
The component is very useful for the generation of components but in my the opinion
the lint package is not necessary. In my case I use the default of vue-cli and the configuration 
is different.

Thank you for the component!  :1st_place_medal:

**Comment by Akryum** [comment]
I didn't understand what your issue was precisely. You tried selecting `less` while creating the project and you ended up with the less packages missing?

Also, I may add multiple choices for the linting at some point.

**Comment by santiblanko** [comment]
No. I don't select any css preprocessor and it's fails.

**Comment by Akryum** [comment]
When did you have this issue?

**Comment by santiblanko** [comment]
Last night. I try to use your tool to generate my new search component.
santiblanko.github.io/#/builder

See the error in asciinema:
https://asciinema.org/a/3ynzs6hgv5m5oykgyge7pw5jg

**Comment by Akryum** [comment]
It should be fine now, I didn't merge dev into master branch. 😄
