### ISSUE TITLE
You may need an appropriate loader to handle this file type (.common)

### ISSUE THREAD

**Issue by altinselimi** [Akryum/vue-share-components#13]
When using the component in a vue project, I receive the following error when running the `npm start` script:

```
You may need an appropriate loader to handle this file type.
| export default from './dist/flatelect.common'
| export * from './dist/flatelect.common'
| import './dist/flatelect.css'
```

I'm using webpack as a module bundler.

**Comment by Akryum** [comment]
Like said in the template, you have to setup a loader that recognize `.css` files.

**Comment by altinselimi** [comment]
I removed the .css line all together but it still doesn't work.

    You may need an appropriate loader to handle this file type.
    export default from './dist/flatelect.common';
    export * from './dist/flatelect.common';

**Comment by altinselimi** [comment]
@Akryum man I would really appreciate some help here. I made a couple of components I'd like to publish on npm so everyone can use but can't due to the error mentioned above. I have removed the css entirely and the error is still there...

**Comment by dmattia** [comment]
@Akryum Could you give an example of this? Is it done on the client side or on the library creator side?

**Comment by Akryum** [comment]
Client side. If the package user can't recognize imports of css files, it will not work.
