### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by giorgiomen** [Akryum/vue-share-components#15]
Hi,
i'm using your template, but when I try to include it in a project, console shows me "Failed to mount component: template or render function not defined.".
Could you help me?
I've published it on npm and its name is 'vue-is-visible'.

Thank you

**Comment by Akryum** [comment]
What is the code where you use it?

**Comment by giorgiomen** [comment]
I'm using it to generate the npm package the url is 
https://github.com/giorgiomen/vue-is-visible

npm install vue-is-visible

and in the Vue file 

import VueIsVisible from 'vue-is-visible'

and when I use it 


&lt;VueIsVisible&gt;&lt;/VueIsVisible&gt;


in console I find that error.
I'm new in Vue development and I can't find a way.

Thank you.

**Comment by sdellis** [comment]
I have a similar problem. Just trying to import the Test component that comes in this repo, I get no errors, but it just doesn't display and its markup is missing when I go to inspect it. The vue dev-tools extension sees it and lists it as an "anonymous" component.

**Comment by sdellis** [comment]
Actually, I figured it out.

I was doing this:
`import Test from 'test-components'`

You have to import it as a member like this: 
`import {Test} from 'test-components'`

**Comment by raffaeu** [comment]
@sdellis Thank you, I was going nuts too and forgot that if your library has more than one component, it should be imported as you mentioned

**Comment by WojciechOsak** [comment]
> Actually, I figured it out.
> 
> I was doing this:
> `import Test from 'test-components'`
> 
> You have to import it as a member like this:
> `import {Test} from 'test-components'`

Thank you! One hour of research and it now works, simple error but really hard to fix, thanks for solution! :)
